
[theme]
base="dark"
primaryColor="#cc0044"
textColor="white"
backgroundColor="#000000"
secondaryBackgroundColor="#220000"
linkColor="#cc0044"
codeBackgroundColor="#000000"

baseRadius = "1.2rem"
#borderColor = "#440023"
showWidgetBorder = true
baseFontSize = 14

[server]
maxUploadSize = 400
